In [1]:
import numpy as np
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x=x/np.amax(x,axis=0)
actual_output=y/100
print(x)
print(actual_output)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def d_sigmoid(x):
    return x*(1-x)

In [3]:
epoch=1000
learning_rate=0.15
input_layer=2
hidden=3
output=1

wh=np.random.uniform(low=-0.05,high=0.05,size=(input_layer,hidden))
print(wh)
bh=np.random.uniform(low=-0.05,high=0.05,size=(1,hidden))
wo=np.random.uniform(low=-0.05,high=0.05,size=(hidden,output))
bo=np.random.uniform(low=-0.05,high=0.05,size=(1,output))

[[ 0.02655422 -0.03700649 -0.02834953]
 [-0.00485699 -0.03037578 -0.01211292]]


In [4]:

for i in range(epoch):
    net_h=np.dot(x,wh)+bh
    sigma=sigmoid(net_h)
    net_o=np.dot(sigma,wo)+bo
    output=sigmoid(net_o)
    
    eo=actual_output-output
    outgard=d_sigmoid(output)
    d_output=eo*outgard
    
    eh=d_output.dot(wo.T)
    hiddengard=d_sigmoid(sigma)
    d_hidden=eh*hiddengard
    
    wo+=sigma.T.dot(d_output)*learning_rate
    wh+=x.T.dot(d_hidden)*learning_rate
    
    sum_error=0
    for j in range(len(actual_output)):
        print(output[j],actual_output[j])
        sum_error=((output[j]-actual_output[j])**2)
    sum_error/=2
print(f'epoch{i},error{sum_error}')

[0.48558225] [0.92]
[0.48551276] [0.86]
[0.48561208] [0.89]
[0.49379293] [0.92]
[0.49377007] [0.86]
[0.49382694] [0.89]
[0.50184506] [0.92]
[0.50186777] [0.86]
[0.50188315] [0.89]
[0.50973771] [0.92]
[0.50980325] [0.86]
[0.5097797] [0.89]
[0.51747043] [0.92]
[0.51757455] [0.86]
[0.51751606] [0.89]
[0.52504319] [0.92]
[0.52518035] [0.86]
[0.52509215] [0.89]
[0.53245634] [0.92]
[0.53261993] [0.86]
[0.53250827] [0.89]
[0.53971056] [0.92]
[0.53989309] [0.86]
[0.53976505] [0.89]
[0.54680683] [0.92]
[0.54700009] [0.86]
[0.54686346] [0.89]
[0.55374643] [0.92]
[0.55394166] [0.86]
[0.55380471] [0.89]
[0.56053083] [0.92]
[0.56071888] [0.86]
[0.56059029] [0.89]
[0.56716174] [0.92]
[0.56733321] [0.86]
[0.56722189] [0.89]
[0.57364105] [0.92]
[0.57378639] [0.86]
[0.57370137] [0.89]
[0.57997079] [0.92]
[0.58008046] [0.86]
[0.5800308] [0.89]
[0.58615316] [0.92]
[0.58621767] [0.86]
[0.58621235] [0.89]
[0.59219046] [0.92]
[0.59220048] [0.86]
[0.59224834] [0.89]
[0.59808511] [0.92]
[0.59803154] [0.86]
[0

In [5]:
print('input',str(x))
print('actual_output',str(actual_output))
print('predicted',output)


input [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual_output [[0.92]
 [0.86]
 [0.89]]
predicted [[0.89624507]
 [0.87855732]
 [0.89508051]]
